---
title: "Regression and Other Stories: Height and weight"
author: "Andrew Gelman, Jennifer Hill, Aki Vehtari"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
---
Tidyverse version by Bill Behrman.

Predict weight from height. See Chapters 3, 9 and 10 in Regression
and Other Stories.

-------------

```{r, message=FALSE}
# Packages
library(tidyverse)

# Parameters
  # Earnings and demographic data
file_earnings <- here::here("Earnings/data/earnings.csv")
  # Common code
file_common <- here::here("_common.R")

#===============================================================================

# Run common code
source(file_common)
```

# Chapter 3

## Data

```{r, message=FALSE}
earnings <- read_csv(file_earnings)

glimpse(earnings)
```

## Plots

```{r}
height_men_mean <- 69.1
height_men_sd <- 2.9
height_women_mean <- 63.7
height_women_sd <- 2.7
n_points <- 101

v <- 
  tibble(
    sex = "Men",
    x = 
      seq(
        height_men_mean - 3 * height_men_sd,
        height_men_mean + 3 * height_men_sd,
        length.out = n_points
      ),
    y = dnorm(x, mean = height_men_mean, sd = height_men_sd)
  ) %>% 
  bind_rows(
    tibble(
      sex = "Women",
      x = 
        seq(
          height_women_mean - 3 * height_women_sd,
          height_women_mean + 3 * height_women_sd,
          length.out = n_points
        ),
      y = dnorm(x, mean = height_women_mean, sd = height_women_sd)
    )
  )

v %>% 
  ggplot(aes(x, y, color = sex)) +
  geom_line() +
  scale_y_continuous(breaks = NULL) +
  scale_color_discrete(direction = -1) +
  labs(
    title = "Heights by gender (normal distributions)",
    x = "Height (inches)",
    y = NULL,
    color = NULL
  )
```

```{r}
earnings %>% 
  ggplot(aes(height)) +
  geom_density(adjust = 1.5) +
  scale_y_continuous(breaks = NULL) +
  labs(
    title = "Heights of all adults (not a normal distribution)",
    x = "Height (inches)",
    y = NULL
  )
```

